language: c
sudo: required
dist: trusty
os:
- linux

before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update;sudo apt-get install gcc-multilib; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install librdkafka-dev librdkafka-dev:i386; fi

script:
- make all